### ISSUE TITLE
Import alignment

### ISSUE THREAD

**Issue by tristanpwdennis** [giffordlabcvr/gluetools#3]
Upon trying to tab complete 'create alignment':
Mode path: /project/ERV
Option load-save-path: /Users/tristandennis/DIGS/ctl
GLUE> create alignment 12:05:13.614 CommandCompleter WARNING: Failed to instantiate command completer class uk.ac.gla.cvr.gluetools.core.command.project.CreateAlignmentCommand.Completer
12:05:13.615 CommandCompleter WARNING: java.lang.NoSuchMethodException: uk.ac.gla.cvr.gluetools.core.command.project.CreateAlignmentCommand$Completer.<init>()
12:05:13.894 CommandCompleter WARNING: Failed to instantiate command completer class uk.ac.gla.cvr.gluetools.core.command.project.CreateAlignmentCommand.Completer
12:05:13.894 CommandCompleter WARNING: java.lang.NoSuchMethodException: uk.ac.gla.cvr.gluetools.core.command.project.CreateAlignmentCommand$Completer.<init>(

**Comment by joshsinger** [comment]
This will be fixed in the next release.
