### ISSUE TITLE
Importing alignments

### ISSUE THREAD

**Issue by jsede** [giffordlabcvr/gluetools#8]
I've been working through the example project and some of the other virus projects. My version (the precompiled version) always seems to get stuck when importing alignments.

In the example project, I get an error after this command:
module unconstrainedAlignmentImporter import AL_UNCONSTRAINED -f alignments/SmithAlignment_23_1_2016_modified.fna

With the output:
[Fatal Error] :1:1: Premature end of file.
Error: XML parse exception: Premature end of file.
Cause: Premature end of file.

I'm running it on a mac with java 1.8.0_172 and MySQL 8.0.13

Thanks!

**Comment by joshsinger** [comment]
Hi there, 

I've got an inkling this will be something BLAST-related. To debug it, we should change a couple of console settings and re-run it.

At the GLUE command-line, in root command mode, type:

GLUE> console set log-level FINEST
GLUE> console set verbose-error true

Then re-build the project
GLUE> run exampleProject.glue

This time, when you hit the error, there should be a lot more output produced. Can you paste this output here?

Thanks!

Josh S.

**Comment by jsede** [comment]
Thanks Josh.

The relevant part is shown at the bottom but I've also attached the full output and my config file here if you want take a look at that.

[GLUE.output.v1.txt](https://github.com/giffordlabcvr/gluetools/files/2552803/GLUE.output.v1.txt)
[gluetools-config.xml.txt](https://github.com/giffordlabcvr/gluetools/files/2552804/gluetools-config.xml.txt)

---

GLUE> # import unconstrained alignment  
GLUE> # The alignment is based on Smith, et. al 2016, but has also been modified to:
GLUE> # 1. Replace internal NN's with --'s for KJ873911 in order to make blast fasta importer work properly.
GLUE> # 2. Add a row for sequence RR_L08816 -- this sequence is present in order to provide feature locations
GLUE> # 3. The missing subtype has been added for JQ013791 (3ra) KJ013415 (3ra) and EU723513 (3f)
GLUE> module unconstrainedAlignmentImporter import AL_UNCONSTRAINED -f alignments/SmithAlignment_23_1_2016_modified.fna
21:45:12.801 GlueLogger FINEST: Fasta ID RR_L08816 was mapped to sequence ncbi-refseqs/L08816
21:45:12.820 ProcessUtils FINE: Running external process: /Users/jseden/builds/ncbi-blast-2.7.1/bin/makeblastdb -in - -dbtype nucl -title "Temporary BLAST DB e7806fb3-9452-4d98-8eb7-28b74946b1de in project example" -out /Users/jseden/builds/gluetools/tmp/blastdbs/example/temp_e7806fb3-9452-4d98-8eb7-28b74946b1de/blastDB
21:45:12.849 ProcessUtils FINE: Running external process: /Users/jseden/builds/ncbi-blast-2.7.1/bin/blastn -db /Users/jseden/builds/gluetools/tmp/blastdbs/example/temp_e7806fb3-9452-4d98-8eb7-28b74946b1de/blastDB -outfmt 14 -num_threads 4
[Fatal Error] :1:1: Premature end of file.
21:45:12.883 GlueLogger FINE: BLAST stderr:
BLAST query/options error: Please provide a file name for outfmt 14.
Please refer to the BLAST+ user manual.

Exception at line 48 of exampleProject.glue
Error: XML parse exception: Premature end of file.
uk.ac.gla.cvr.gluetools.utils.GlueXmlUtilsException
uk.ac.gla.cvr.gluetools.utils.GlueXmlUtils.documentsFromBytes(GlueXmlUtils.java:357)
uk.ac.gla.cvr.gluetools.programs.blast.BlastRunner.executeBlastUsingStreams(BlastRunner.java:194)
uk.ac.gla.cvr.gluetools.programs.blast.BlastRunner.executeBlast(BlastRunner.java:105)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.BlastFastaAlignmentImporter.findAlignedSegs(BlastFastaAlignmentImporter.java:125)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.FastaNtAlignmentImporter.doImport(FastaNtAlignmentImporter.java:178)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.BlastFastaAlignmentImporterImportCommand.execute(BlastFastaAlignmentImporterImportCommand.java:86)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.BlastFastaAlignmentImporterImportCommand.execute(BlastFastaAlignmentImporterImportCommand.java:52)
uk.ac.gla.cvr.gluetools.core.command.project.module.ModulePluginCommand.execute(ModulePluginCommand.java:58)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:259)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:243)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:205)
uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:179)
uk.ac.gla.cvr.gluetools.core.console.Console.runBatchCommands(Console.java:640)
uk.ac.gla.cvr.gluetools.core.command.console.ConsoleCommandContext.runBatchCommands(ConsoleCommandContext.java:330)
uk.ac.gla.cvr.gluetools.core.command.console.RunFileCommand.execute(RunFileCommand.java:80)
uk.ac.gla.cvr.gluetools.core.command.console.RunFileCommand.execute(RunFileCommand.java:44)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:259)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:205)
uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:179)
uk.ac.gla.cvr.gluetools.core.console.Console.handleInteractiveLine(Console.java:127)
uk.ac.gla.cvr.gluetools.core.console.Console.interactiveSession(Console.java:504)
uk.ac.gla.cvr.gluetools.core.console.Console.access$800(Console.java:92)
uk.ac.gla.cvr.gluetools.core.console.Console$1.get(Console.java:402)
uk.ac.gla.cvr.gluetools.core.console.Console$1.get(Console.java:392)
uk.ac.gla.cvr.gluetools.core.GluetoolsEngine.runWithGlueClassloader(GluetoolsEngine.java:265)
uk.ac.gla.cvr.gluetools.core.console.Console.main(Console.java:392)
Cause: Premature end of file.
org.xml.sax.SAXParseException
com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
uk.ac.gla.cvr.gluetools.utils.GlueXmlUtils.documentFromStream(GlueXmlUtils.java:76)
uk.ac.gla.cvr.gluetools.utils.GlueXmlUtils.documentsFromBytes(GlueXmlUtils.java:355)
uk.ac.gla.cvr.gluetools.programs.blast.BlastRunner.executeBlastUsingStreams(BlastRunner.java:194)
uk.ac.gla.cvr.gluetools.programs.blast.BlastRunner.executeBlast(BlastRunner.java:105)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.BlastFastaAlignmentImporter.findAlignedSegs(BlastFastaAlignmentImporter.java:125)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.FastaNtAlignmentImporter.doImport(FastaNtAlignmentImporter.java:178)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.BlastFastaAlignmentImporterImportCommand.execute(BlastFastaAlignmentImporterImportCommand.java:86)
uk.ac.gla.cvr.gluetools.core.collation.importing.fasta.alignment.BlastFastaAlignmentImporterImportCommand.execute(BlastFastaAlignmentImporterImportCommand.java:52)
uk.ac.gla.cvr.gluetools.core.command.project.module.ModulePluginCommand.execute(ModulePluginCommand.java:58)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:259)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:243)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:205)
uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:179)
uk.ac.gla.cvr.gluetools.core.console.Console.runBatchCommands(Console.java:640)
uk.ac.gla.cvr.gluetools.core.command.console.ConsoleCommandContext.runBatchCommands(ConsoleCommandContext.java:330)
uk.ac.gla.cvr.gluetools.core.command.console.RunFileCommand.execute(RunFileCommand.java:80)
uk.ac.gla.cvr.gluetools.core.command.console.RunFileCommand.execute(RunFileCommand.java:44)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:259)
uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:205)
uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:179)
uk.ac.gla.cvr.gluetools.core.console.Console.handleInteractiveLine(Console.java:127)
uk.ac.gla.cvr.gluetools.core.console.Console.interactiveSession(Console.java:504)
uk.ac.gla.cvr.gluetools.core.console.Console.access$800(Console.java:92)
uk.ac.gla.cvr.gluetools.core.console.Console$1.get(Console.java:402)
uk.ac.gla.cvr.gluetools.core.console.Console$1.get(Console.java:392)
uk.ac.gla.cvr.gluetools.core.GluetoolsEngine.runWithGlueClassloader(GluetoolsEngine.java:265)
uk.ac.gla.cvr.gluetools.core.console.Console.main(Console.java:392)

**Comment by joshsinger** [comment]
Hi, 

Thanks for the debug information.

I've previously only tested GLUE with older versions of BLAST+ -- for reference I use v2.2.31. I am 99% sure that what's happened here is that in later versions the BLAST+ developers have changed the default behaviour which was to output the results to stdout, as expected by GLUE. Hence there is a message from BLAST+ 2.7.1 on stderr asking for a file name to be provided.

If this is the case I will make GLUE use temporary files with BLAST+ rather than streams (I'm already doing this in some scenarios anyway). 

The only issue right now is that I'm unable to test my theory on BLAST+ 2.7.1 because the NCBI ftp site is down. I'll give it a go as soon as that site is up again.

cheers

josh

**Comment by jsede** [comment]
With Blast-2.2.31 things are now working. It must be a very version specific issue because when you first mentioned it might be blast I actually tried it with v2.2.29, v.2.5.1 and v2.7.1 and all failed.

Thanks again for looking at this. Happy to test anything here if you need me to.

J-S
